package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2013-02-13T13:49:24.858-04:30
 * Generated source version: 2.6.2
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "TempConvertHttpPost")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface TempConvertHttpPost {

    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "FahrenheitToCelsius")
    public java.lang.String fahrenheitToCelsius(
        @WebParam(partName = "Fahrenheit", name = "Fahrenheit", targetNamespace = "http://tempuri.org/")
        java.lang.String fahrenheit
    );

    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "CelsiusToFahrenheit")
    public java.lang.String celsiusToFahrenheit(
        @WebParam(partName = "Celsius", name = "Celsius", targetNamespace = "http://tempuri.org/")
        java.lang.String celsius
    );
}
